<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<div "result">A test is run (UNDEFINED)</div>]]>
    </line>
    <line>
      <![CDATA[<div "result">the test is passed (SKIPPED)</div>]]>
    </line>
    <line>
      <![CDATA[<div "result">the passed test is logged (SKIPPED)</div>]]>
    </line>
    <line>
      <![CDATA[<div "result">A failed test is run (UNDEFINED)</div>]]>
    </line>
    <line>
      <![CDATA[<div "result">the test is failed (SKIPPED)</div>]]>
    </line>
    <line>
      <![CDATA[<div "result">the failed test is logged (SKIPPED)</div>]]>
    </line>
  </reporter-output>
  <suite name="Log Suite Example" duration-ms="645" started-at="2018-07-23T16:20:47Z" finished-at="2018-07-23T16:20:47Z">
    <groups>
      <group name="cucumber scenarios">
        <method signature="TestRunner.scenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.cucumber.dblogging.ResultLogging.TestRunner@5e3a8624]" name="scenario" class="com.cucumber.dblogging.ResultLogging.TestRunner"/>
      </group> <!-- cucumber scenarios -->
    </groups>
    <test name="TestNG logs sample" duration-ms="645" started-at="2018-07-23T16:20:47Z" finished-at="2018-07-23T16:20:47Z">
      <class name="com.cucumber.dblogging.ResultLogging.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.cucumber.dblogging.ResultLogging.TestRunner@5e3a8624]" name="setUpClass" is-config="true" duration-ms="254" started-at="2018-07-23T16:20:47Z" finished-at="2018-07-23T16:20:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="SKIP" signature="scenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.cucumber.dblogging.ResultLogging.TestRunner@5e3a8624]" name="scenario" duration-ms="54" started-at="2018-07-23T16:20:47Z" description="Runs Cucumber scenarios" data-provider="scenarios" finished-at="2018-07-23T16:20:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Test if passed test is logged properly"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Testing the ResultLogging Feature"]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[There are undefined steps]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: There are undefined steps
at cucumber.api.testng.TestCaseResultListener.getError(TestCaseResultListener.java:58)
at cucumber.api.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:59)
at com.cucumber.dblogging.ResultLogging.TestRunner.scenario(TestRunner.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
            <line>
              <![CDATA[<div "result">A test is run (UNDEFINED)</div>]]>
            </line>
            <line>
              <![CDATA[<div "result">the test is passed (SKIPPED)</div>]]>
            </line>
            <line>
              <![CDATA[<div "result">the passed test is logged (SKIPPED)</div>]]>
            </line>
          </reporter-output>
        </test-method> <!-- scenario -->
        <test-method status="SKIP" signature="scenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.cucumber.dblogging.ResultLogging.TestRunner@5e3a8624]" name="scenario" duration-ms="4" started-at="2018-07-23T16:20:47Z" description="Runs Cucumber scenarios" data-provider="scenarios" finished-at="2018-07-23T16:20:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Test if failed test is logged properly"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Testing the ResultLogging Feature"]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[There are undefined steps]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: There are undefined steps
at cucumber.api.testng.TestCaseResultListener.getError(TestCaseResultListener.java:58)
at cucumber.api.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:59)
at com.cucumber.dblogging.ResultLogging.TestRunner.scenario(TestRunner.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
            <line>
              <![CDATA[<div "result">A failed test is run (UNDEFINED)</div>]]>
            </line>
            <line>
              <![CDATA[<div "result">the test is failed (SKIPPED)</div>]]>
            </line>
            <line>
              <![CDATA[<div "result">the failed test is logged (SKIPPED)</div>]]>
            </line>
          </reporter-output>
        </test-method> <!-- scenario -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:com.cucumber.dblogging.ResultLogging.TestRunner@5e3a8624]" name="tearDownClass" is-config="true" duration-ms="11" started-at="2018-07-23T16:20:47Z" finished-at="2018-07-23T16:20:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.cucumber.dblogging.ResultLogging.TestRunner -->
    </test> <!-- TestNG logs sample -->
  </suite> <!-- Log Suite Example -->
</testng-results>
